const data = [
    {
      username: "amit sharma",
      email: "amitsharma123@gmail.com",
      password: "Amit@2024",
      category: ["Adventure and Thrill Park", "Mountain and Hiking Destinations", "Beaches and Coastal Areas"],
    },
    {
      username: "sneha verma",
      email: "snehav@gmail.com",
      password: "Sneha@2024",
      category: ["Museums and Art Galleries", "Historical and Heritage Sites", "Beaches and Coastal Areas"],
    },
    {
      username: "rajat gupta",
      email: "rajatg99@gmail.com",
      password: "Rajat@2024",
      category: ["Wildlife Reserves and Sanctuaries", "Sports and Recreation Grounds"],
    },
    {
      username: "priya kapoor",
      email: "priyakapoor12@gmail.com",
      password: "Priya@2024",
      category: ["Religious and Cultural Sites", "Beaches and Coastal Areas"],
    },
    {
      username: "rahul singh",
      email: "rahulsingh88@gmail.com",
      password: "Rahul@2024",
      category: ["Adventure and Thrill Park", "Sports and Recreation Grounds"],
    },
    {
      username: "ananya mishra",
      email: "ananyam@gmail.com",
      password: "Ananya@2024",
      category: ["Historical and Heritage Sites", "Religious and Cultural Sites", "Beaches and Coastal Areas"],
    },
    {
      username: "vivek das",
      email: "vivekd98@gmail.com",
      password: "Vivek@2024",
      category: ["Mountain and Hiking Destinations"],
    },
    {
      username: "neha chopra",
      email: "nehac@gmail.com",
      password: "Neha@2024",
      category: ["Museums and Art Galleries", "Adventure and Thrill Park", "Beaches and Coastal Areas"],
    },
    {
      username: "akash patil",
      email: "akashp@gmail.com",
      password: "Akash@2024",
      category: ["Wildlife Reserves and Sanctuaries"],
    },
    {
      username: "rishabh mehta",
      email: "rishabhm@gmail.com",
      password: "Rishabh@2024",
      category: ["Religious and Cultural Sites", "Historical and Heritage Sites", "Beaches and Coastal Areas"],
    },
    {
      username: "komal sen",
      email: "komalsen01@gmail.com",
      password: "Komal@2024",
      category: ["Sports and Recreation Grounds"],
    },
    {
      username: "tarun malhotra",
      email: "tarunm@gmail.com",
      password: "Tarun@2024",
      category: ["Mountain and Hiking Destinations", "Wildlife Reserves and Sanctuaries"],
    },
    {
      username: "divya iyer",
      email: "divyai@gmail.com",
      password: "Divya@2024",
      category: ["Historical and Heritage Sites"],
    },
    {
      username: "manoj saxena",
      email: "manojs@gmail.com",
      password: "Manoj@2024",
      category: ["Museums and Art Galleries", "Religious and Cultural Sites"],
    },
    {
      username: "swati jain",
      email: "swatij@gmail.com",
      password: "Swati@2024",
      category: ["Adventure and Thrill Park"],
    },
    {
      username: "deepak nayak",
      email: "deepakn@gmail.com",
      password: "Deepak@2024",
      category: ["Wildlife Reserves and Sanctuaries", "Museums and Art Galleries"],
    },
    {
      username: "riya sharma",
      email: "riyash@gmail.com",
      password: "Riya@2024",
      category: ["Mountain and Hiking Destinations"],
    },
    {
      username: "suresh pillai",
      email: "sureshp@gmail.com",
      password: "Suresh@2024",
      category: ["Religious and Cultural Sites", "Historical and Heritage Sites"],
    },
    {
      username: "harsh agarwal",
      email: "harsha@gmail.com",
      password: "Harsh@2024",
      category: ["Sports and Recreation Grounds"],
    },
    {
      username: "megha singh",
      email: "meghas@gmail.com",
      password: "Megha@2024",
      category: ["Adventure and Thrill Park", "Wildlife Reserves and Sanctuaries", "Beaches and Coastal Areas"],
    },
    {
      username: "rohit mishra",
      email: "rohitm@gmail.com",
      password: "Rohit@2024",
      category: ["Museums and Art Galleries"],
    },
    {
      username: "shreya kulkarni",
      email: "shreyak@gmail.com",
      password: "Shreya@2024",
      category: ["Historical and Heritage Sites", "Sports and Recreation Grounds"],
    },
    {
      username: "abhishek patil",
      email: "abhishekp@gmail.com",
      password: "Abhishek@2024",
      category: ["Wildlife Reserves and Sanctuaries"],
    },
    {
      username: "pallavi rane",
      email: "pallavir@gmail.com",
      password: "Pallavi@2024",
      category: ["Mountain and Hiking Destinations", "Museums and Art Galleries", "Beaches and Coastal Areas"],
    },
    {
      username: "naveen sharma",
      email: "naveens@gmail.com",
      password: "Naveen@2024",
      category: ["Religious and Cultural Sites"],
    },
    {
      username: "kavita das",
      email: "kavitad@gmail.com",
      password: "Kavita@2024",
      category: ["Adventure and Thrill Park", "Historical and Heritage Sites"],
    },
    {
      username: "sanjay pawar",
      email: "sanjayp@gmail.com",
      password: "Sanjay@2024",
      category: ["Museums and Art Galleries", "Sports and Recreation Grounds"],
    },
    {
      username: "payal bose",
      email: "payalb@gmail.com",
      password: "Payal@2024",
      category: ["Wildlife Reserves and Sanctuaries"],
    },
    {
      username: "vikram chopra",
      email: "vikramc@gmail.com",
      password: "Vikram@2024",
      category: ["Mountain and Hiking Destinations", "Religious and Cultural Sites"],
    },
    {
      username: "anjali mehta",
      email: "anjalim@gmail.com",
      password: "Anjali@2024",
      category: ["Historical and Heritage Sites"],
    },
    {
      username: "arjun singh",
      email: "arjuns@gmail.com",
      password: "Arjun@2024",
      category: ["Adventure and Thrill Park", "Mountain and Hiking Destinations"],
    },
    {
      username: "tanvi sharma",
      email: "tanvis@gmail.com",
      password: "Tanvi@2024",
      category: ["Museums and Art Galleries", "Historical and Heritage Sites", "Beaches and Coastal Areas"],
    },
    {
      username: "rohan kapoor",
      email: "rohank@gmail.com",
      password: "Rohan@2024",
      category: ["Wildlife Reserves and Sanctuaries", "Sports and Recreation Grounds"],
    },
    {
      username: "kritika verma",
      email: "kritikav@gmail.com",
      password: "Kritika@2024",
      category: ["Religious and Cultural Sites"],
    },
    {
      username: "devansh gupta",
      email: "devanshg@gmail.com",
      password: "Devansh@2024",
      category: ["Adventure and Thrill Park", "Sports and Recreation Grounds"],
    },
    {
      username: "isha malhotra",
      email: "isham@gmail.com",
      password: "Isha@2024",
      category: ["Historical and Heritage Sites", "Religious and Cultural Sites"],
    },
    {
      username: "gautam nair",
      email: "gautamn@gmail.com",
      password: "Gautam@2024",
      category: ["Mountain and Hiking Destinations"],
    },
    {
      username: "riya mehta",
      email: "riyamehta@gmail.com",
      password: "Riya@2024",
      category: ["Museums and Art Galleries", "Adventure and Thrill Park"],
    },
    {
      username: "siddharth saxena",
      email: "siddharths@gmail.com",
      password: "Siddharth@2024",
      category: ["Wildlife Reserves and Sanctuaries"],
    },
    {
      username: "shruti jain",
      email: "shrutij@gmail.com",
      password: "Shruti@2024",
      category: ["Religious and Cultural Sites", "Historical and Heritage Sites"],
    },
    {
      username: "vaibhav patel",
      email: "vaibhavp@gmail.com",
      password: "Vaibhav@2024",
      category: ["Sports and Recreation Grounds"],
    },
    {
      username: "meera sharma",
      email: "meeras@gmail.com",
      password: "Meera@2024",
      category: ["Mountain and Hiking Destinations", "Wildlife Reserves and Sanctuaries"],
    },
    {
      username: "harish nayak",
      email: "harishn@gmail.com",
      password: "Harish@2024",
      category: ["Historical and Heritage Sites"],
    },
    {
      username: "kiran iyer",
      email: "kirani@gmail.com",
      password: "Kiran@2024",
      category: ["Museums and Art Galleries", "Religious and Cultural Sites"],
    },
    {
      username: "shivani rao",
      email: "shivanir@gmail.com",
      password: "Shivani@2024",
      category: ["Adventure and Thrill Park"],
    },
    {
      username: "vishal bhatt",
      email: "vishalb@gmail.com",
      password: "Vishal@2024",
      category: ["Wildlife Reserves and Sanctuaries", "Museums and Art Galleries"],
    },
    {
      username: "pranav pillai",
      email: "pranavp@gmail.com",
      password: "Pranav@2024",
      category: ["Mountain and Hiking Destinations"],
    },
    {
      username: "sanya arora",
      email: "sanyaa@gmail.com",
      password: "Sanya@2024",
      category: ["Religious and Cultural Sites", "Historical and Heritage Sites"],
    },
    {
      username: "deepesh agarwal",
      email: "deepesha@gmail.com",
      password: "Deepesh@2024",
      category: ["Sports and Recreation Grounds"],
    },
    {
      username: "soumya gupta",
      email: "soumyag@gmail.com",
      password: "Soumya@2024",
      category: ["Adventure and Thrill Park", "Wildlife Reserves and Sanctuaries", "Beaches and Coastal Areas"],
    },
    {
      username: "nishant mishra",
      email: "nishantm@gmail.com",
      password: "Nishant@2024",
      category: ["Museums and Art Galleries"],
    },
    {
      username: "piyush kulkarni",
      email: "piyushk@gmail.com",
      password: "Piyush@2024",
      category: ["Historical and Heritage Sites", "Sports and Recreation Grounds"],
    },
    {
      username: "simran patil",
      email: "simranp@gmail.com",
      password: "Simran@2024",
      category: ["Wildlife Reserves and Sanctuaries"],
    },
    {
      username: "ritika rane",
      email: "ritikar@gmail.com",
      password: "Ritika@2024",
      category: ["Mountain and Hiking Destinations", "Museums and Art Galleries"],
    },
    {
      username: "karan sharma",
      email: "karans@gmail.com",
      password: "Karan@2024",
      category: ["Religious and Cultural Sites"],
    },
    {
      username: "pooja das",
      email: "poojad@gmail.com",
      password: "Pooja@2024",
      category: ["Adventure and Thrill Park", "Historical and Heritage Sites"],
    },
    {
      username: "rahul pawar",
      email: "rahulp@gmail.com",
      password: "Rahul@2024",
      category: ["Museums and Art Galleries", "Sports and Recreation Grounds"],
    },
    {
      username: "tanya bose",
      email: "tanyab@gmail.com",
      password: "Tanya@2024",
      category: ["Wildlife Reserves and Sanctuaries"],
    },
    {
      username: "anirudh chopra",
      email: "anirudhc@gmail.com",
      password: "Anirudh@2024",
      category: ["Mountain and Hiking Destinations", "Religious and Cultural Sites"],
    },
    {
      username: "sakshi mehta",
      email: "sakshim@gmail.com",
      password: "Sakshi@2024",
      category: ["Historical and Heritage Sites"],
    },
    // New users (30 additional users)
    {
      username: "aditya verma",
      email: "adityav@gmail.com",
      password: "Aditya@2024",
      category: ["Adventure and Thrill Park", "Beaches and Coastal Areas"],
    },
    {
      username: "nisha reddy",
      email: "nishar@gmail.com",
      password: "Nisha@2024",
      category: ["Historical and Heritage Sites", "Museums and Art Galleries"],
    },
    {
      username: "sumit thakur",
      email: "sumitt@gmail.com",
      password: "Sumit@2024",
      category: ["Wildlife Reserves and Sanctuaries", "Mountain and Hiking Destinations"],
    },
    {
      username: "aarti shinde",
      email: "aartis@gmail.com",
      password: "Aarti@2024",
      category: ["Religious and Cultural Sites", "Sports and Recreation Grounds"],
    },
    {
      username: "kunal joshi",
      email: "kunalj@gmail.com",
      password: "Kunal@2024",
      category: ["Adventure and Thrill Park", "Wildlife Reserves and Sanctuaries"],
    },
    {
      username: "sonali rathore",
      email: "sonalir@gmail.com",
      password: "Sonali@2024",
      category: ["Museums and Art Galleries", "Beaches and Coastal Areas"],
    },
    {
      username: "vikas yadav",
      email: "vikasy@gmail.com",
      password: "Vikas@2024",
      category: ["Mountain and Hiking Destinations", "Sports and Recreation Grounds"],
    },
    {
      username: "preeti khanna",
      email: "preetik@gmail.com",
      password: "Preeti@2024",
      category: ["Historical and Heritage Sites", "Religious and Cultural Sites"],
    },
    {
      username: "sameer khan",
      email: "sameerk@gmail.com",
      password: "Sameer@2024",
      category: ["Wildlife Reserves and Sanctuaries", "Beaches and Coastal Areas"],
    },
    {
      username: "anita desai",
      email: "anitad@gmail.com",
      password: "Anita@2024",
      category: ["Adventure and Thrill Park", "Museums and Art Galleries"],
    },
    {
      username: "saurabh bhardwaj",
      email: "saurabhb@gmail.com",
      password: "Saurabh@2024",
      category: ["Sports and Recreation Grounds", "Mountain and Hiking Destinations"],
    },
    {
      username: "jaya prasad",
      email: "jayap@gmail.com",
      password: "Jaya@2024",
      category: ["Religious and Cultural Sites", "Historical and Heritage Sites"],
    },
    {
      username: "nitin gowda",
      email: "niting@gmail.com",
      password: "Nitin@2024",
      category: ["Wildlife Reserves and Sanctuaries", "Adventure and Thrill Park"],
    },
    {
      username: "shilpa naik",
      email: "shilpan@gmail.com",
      password: "Shilpa@2024",
      category: ["Museums and Art Galleries", "Beaches and Coastal Areas"],
    },
    {
      username: "arun kumar",
      email: "arunk@gmail.com",
      password: "Arun@2024",
      category: ["Mountain and Hiking Destinations", "Historical and Heritage Sites"],
    },
    {
      username: "ruchi sharma",
      email: "ruchis@gmail.com",
      password: "Ruchi@2024",
      category: ["Adventure and Thrill Park", "Sports and Recreation Grounds"],
    },
    {
      username: "manish thapa",
      email: "manisht@gmail.com",
      password: "Manish@2024",
      category: ["Wildlife Reserves and Sanctuaries", "Religious and Cultural Sites"],
    },
    {
      username: "snehal kadam",
      email: "snehalk@gmail.com",
      password: "Snehal@2024",
      category: ["Museums and Art Galleries", "Mountain and Hiking Destinations"],
    },
    {
      username: "pratik deshmukh",
      email: "pratikd@gmail.com",
      password: "Pratik@2024",
      category: ["Historical and Heritage Sites", "Beaches and Coastal Areas"],
    },
    {
      username: "vidya balan",
      email: "vidyab@gmail.com",
      password: "Vidya@2024",
      category: ["Adventure and Thrill Park", "Wildlife Reserves and Sanctuaries"],
    },
    {
      username: "rohan desai",
      email: "rohand@gmail.com",
      password: "Rohan@2024",
      category: ["Sports and Recreation Grounds", "Religious and Cultural Sites"],
    },
    {
      username: "kirti patel",
      email: "kirtip@gmail.com",
      password: "Kirti@2024",
      category: ["Mountain and Hiking Destinations", "Beaches and Coastal Areas"],
    },
    {
      username: "amrita singh",
      email: "amritas@gmail.com",
      password: "Amrita@2024",
      category: ["Museums and Art Galleries", "Historical and Heritage Sites"],
    },
    {
      username: "sahil more",
      email: "sahilm@gmail.com",
      password: "Sahil@2024",
      category: ["Wildlife Reserves and Sanctuaries", "Sports and Recreation Grounds"],
    },
    {
      username: "neelam gupta",
      email: "neelamg@gmail.com",
      password: "Neelam@2024",
      category: ["Adventure and Thrill Park", "Religious and Cultural Sites"],
    },
    {
      username: "ajay rao",
      email: "ajayr@gmail.com",
      password: "Ajay@2024",
      category: ["Mountain and Hiking Destinations", "Museums and Art Galleries"],
    },
    {
      username: "rekha shinde",
      email: "rekhas@gmail.com",
      password: "Rekha@2024",
      category: ["Historical and Heritage Sites", "Wildlife Reserves and Sanctuaries"],
    },
    {
      username: "vivek pawar",
      email: "vivekp@gmail.com",
      password: "Vivek@2024",
      category: ["Sports and Recreation Grounds", "Beaches and Coastal Areas"],
    },
    {
      username: "meenal joshi",
      email: "meenalj@gmail.com",
      password: "Meenal@2024",
      category: ["Adventure and Thrill Park", "Museums and Art Galleries"],
    },
    {
      username: "omkar patil",
      email: "omkarp@gmail.com",
      password: "Omkar@2024",
      category: ["Wildlife Reserves and Sanctuaries", "Mountain and Hiking Destinations"],
    },
  
]